### ISSUE TITLE
Cannot use on OS X

### ISSUE THREAD

**Issue by Bambofy** [microsoft/ClangSharp#117]
Hi,

After installing ClangSharp from the nuget package managaer using Visual Studio for Mac, the program throws errors.

> /Users/richardbamford/.nuget/packages/clangsharp/3.8.0/build/ClangSharp.targets(5,5): Error: ClangSharp requires the platform target for the solution and/or project to be either x86 or x64 to PInvoke appropriately. (rr)

Any idea how to fix this?

**Comment by tannergooding** [comment]
3.8.0 was the last "stable" release but it is over 3 years old at this point and there have been many changes, improvements, etc since then.

I would recommend trying the 8.0.0-beta or 9.0.0-beta package (which correspond to Clang v8.0.0 and v9.0.0, respectively) and seeing if the issue still reproduces.

**Comment by Bambofy** [comment]
Hi,

v9.0.0 works great, the only issue is that i can't seem to find a libclang.dylib when i install this package: https://www.nuget.org/packages/libclang

See attached:
<img width="1044" alt="Screenshot 2020-02-09 at 21 11 19" src="https://user-images.githubusercontent.com/1304898/74110028-cfa7d000-4b80-11ea-81c9-8a47f389743b.png">

I had to use the dylib packaged with this nuget package instead:
https://www.nuget.org/packages/clang.sharp/

**Comment by aspcompiler** [comment]
Instead of install libclang from another place, if you have Xcode installed, you should have libclang.dylib. On my machine (Catalina and latest Xcode), it is in /Library/Developer/CommandLineTools/usr/lib/. I just had to set the environment variable first:

export DYLD_LIBRARY_PATH=/Library/Developer/CommandLineTools/usr/lib

**Comment by tannergooding** [comment]
The issue is likely the same as described in https://github.com/microsoft/ClangSharp/issues/118#issuecomment-598305888. Going to close as a duplicate.
