### ISSUE TITLE
Source generator does not handle the traditional C NULL define correctly.

### ISSUE THREAD

**Issue by jmaine** [microsoft/ClangSharp#149]
The source generator does not handle the traditional C NULL define correctly.

**Comment by tannergooding** [comment]
Can you give an example of the C code that is given, the current C# code that is generated, and what the expected result is?

`NULL` in particular can be difficult to get correct in all cases due to the implicit conversions that C/C++ support which C# does not. So I'm sure there are a few edge cases that were missed.

**Comment by tannergooding** [comment]
Closing as not enough information has been provided. Please feel free to open a new issue with the appropriate repro steps.
