### ISSUE TITLE
libClangSharp.runtime.* build instructions

### ISSUE THREAD

**Issue by rokups** [microsoft/ClangSharp#178]
Would it be possible to get build instructions for `libClangSharp.runtime.*` packages? CI does not build them.

**Comment by tannergooding** [comment]
CI does not currently build it because it is very expensive to do so.

The basic steps are essentially:
1. Clone https://github.com/llvm/llvm-project
2. Build a release configuration of llvm-project by following the instructions provided: http://clang.llvm.org/get_started.html
3. Install the built llvm-project to some folder (generally specified via `CMAKE_INSTALL_PREFIX=path`)
4. Using cmake, build libClangSharp. The cmakelist.txt is in the repo root and specifying `PATH_TO_LLVM=path`, where `path` is the same as specified for the llvm-project `CMAKE_INSTALL_PREFIX`

If on Linux, you *may* be able to skip steps 1-3 by setting `PATH_TO_LLVM` to something like `/usr/lib/llvm-10`, the need is to resolve `lib/cmake/clang/ClangConfig.cmake` and friends which aren't always available for a given install.

**Comment by tannergooding** [comment]
https://github.com/microsoft/ClangSharp/pull/214 adds some basic documentation on building the managed vs native sides.

Please feel free to request additional information or clarification if its needed and I'll work on updating the docs further.

**Comment by tannergooding** [comment]
See https://github.com/microsoft/ClangSharp#building-managed
and https://github.com/microsoft/ClangSharp#building-native
