### ISSUE TITLE
parseTranslationUnit doesn't take a list of CXUnsavedFile

### ISSUE THREAD

**Issue by davidychow87** [microsoft/ClangSharp#77]
I am trying to pass in multiple unsaved files, but it seems that parseTranslationUnit only takes a single CXUnsaved file. I saw that this was reported here:

https://github.com/microsoft/ClangSharp/issues/12

But it appears that it still doesn't accept CXUnsavedFile[].

I am using the latest version: 3.8.0
![image](https://user-images.githubusercontent.com/22185727/61981557-ddb04d80-afae-11e9-8601-1621e4402593.png)

But as you can see, parseTranslationUnit accepts a single CXUnsavedFile
![image](https://user-images.githubusercontent.com/22185727/61981763-6c24cf00-afaf-11e9-8c35-8aa8c0222318.png)

**Comment by tannergooding** [comment]
For 3.8.0, there are additional helper methods that take a `CXUnsavedFile[]` instead. For example: https://github.com/microsoft/ClangSharp/blob/b52de9c08f7243a8f060d511e1d9ed1a901d3cb3/ClangSharp/Generated.Custom.cs#L42

This has all been rewritten since then and there just hasn't been a new NuGet package published yet. Now, the original signature is correct and just takes a `CXUnsavedFile*`: https://github.com/microsoft/ClangSharp/blob/master/sources/ClangSharp/Interop/clang.cs#L218

There are then friendly helper functions such as `CXTranslationUnit.Parse` which don't require the consumer to use `unsafe` code: https://github.com/microsoft/ClangSharp/blob/master/sources/ClangSharp/Interop.Extensions/CXTranslationUnit.cs#L72

The recommended approach with the latest sources, if you are willing to build them locally, would be to create the `CXTranslationUnit` using the latter method and then call `TranslationUnit.GetOrCreate` to get a friendly/type-safe version: https://github.com/microsoft/ClangSharp/blob/master/sources/ClangSharp/TranslationUnit.cs#L39.

You can then use the `TranslationUnit` type for walking/handling most of the AST and falling back to the `.Handle` and direct methods where functionality isn't exposed.

**Comment by tannergooding** [comment]
A preview of the 8.0.0 bits are available on NuGet now, you should be able to use that to test the scenario I mentioned above.
